# Docker image for culling idle notebook servers. Requires a token from 
# JupyterHub, e.g.
#
# export token=$(jupyterhub token -f /path/to/jupyterhub_config.py $JHUB_ADMIN)
# docker run -e "JPY_ADMIN_TOKEN=$token" compmodels/cull \
#             --timeout=86400 \
#             --cull_every=3600 \
#             --url=http://[jupyterhub_ip]:8081/hub

# - name: create the /srv/cull directory
#   file: 
#     path=/srv/cull
#     state=directory

# - name: Copy cull Dockerfile to server
#   copy: 
#     src=cull.Dockerfile
#     dest=/srv/cull/Dockerfile

# - name: Create JupyterHub service folder
#   file: path={{ item[0] }} state={{ item[1] }}
#   with_nested:
#     - [ /srv/cull ]
#     - [ absent, directory ]

- name: Copy cull to host OS
  copy:
    src=cull
    dest=/srv
    mode='0644'

# - name: clone the dockerfile git repository
#   git: repo=https://github.com/AdrianGPrado/docker-jupyterhub-cull.git dest=/srv/cull
