---

- name: build custom docker images
  docker_image:
    name={{ item.name }}
    tag={{ item.tag }}
    path={{ item.path }}
  with_items: '{{ list_docker_custom_images }}'

- name: launch postgres container
  docker:
    name: jpydb
    image: postgres
    state: reloaded
    restart_policy: always
    env:
      POSTGRES_DB: jupyterhub
      POSTGRES_PASSWORD: "{{ jpy_postgres_password }}"
      PGDATA: '{{ postgres_docker_container_PGATA }}'
    volumes:
      - '{{ postgres_docker_host_vol }}:{{ postgres_docker_container_PGATA }}'
