---

- name: build custom docker images
  docker_image:
    name={{ item.name }}
    tag={{ item.tag }}
    path={{ item.path }}
  with_items:
    - name: '{{ docker_cull_img_name }}'
      tag:  '{{ docker_cull_img_custom_tag }}'
      path: '{{ cull_docker_dir }}'
    - name: '{{ docker_stats_img_name }}'
      tag:  '{{ docker_stats_img_custom_tag }}'
      path: '{{ stats_docker_dir }}'
    - name: '{{ docker_jhub_img_name }}'
      tag:  '{{ docker_jhub_img_custom_tag }}'
      path: '{{ jupytherhub_docker_dir }}'

# TODO:
# - Clean old images
#     - Stop containers based on old images
#     - delete the old image
