---

- name: Clean folder structure for jupyterhub
  file: path={{ item[0] }} state={{ item[1] }}
  with_nested:
    - '{{ docker_jupyterhub_dir_structure }}'
    - [ absent, directory ]

- name: Copy Docker configuration files and scripts
  copy:
    src={{ item }}
    dest={{ jupyterhub_work_dir }}
    mode='0644'
  with_items: '{{ docker_images_conf_dif_folders }}'

- name: Create jupyterhub userlist
  template: src=userlist.j2 dest={{ jupyterhub_users_dir }}/userlist
