---
- fail: msg="configproxy_auth_token is not defined"
  when: configproxy_auth_token == ''
- fail: msg="cookie_secret is not defined"
  when: cookie_secret == ''
- fail: msg="admin list is empty"
  when: jupyterhub_admins|length == 0

- name: Create JupyterHub service folder
  file:
  file:
    path: '/srv/jupyterhub'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Copy JupyterHub docker file to server
  copy: 
    src=jupyterhub.Dockerfile
    dest=/srv/jupyterhub/Dockerfile

# - name: create the jupyterhub_users directory
#   file: path=/srv/jupyterhub_users state=directory

# - name: create the userlist
#   template: src=userlist.j2 dest=/srv/jupyterhub_users/userlist
