---
- fail: msg="configproxy_auth_token is not defined"
  when: configproxy_auth_token == ''
- fail: msg="cookie_secret is not defined"
  when: cookie_secret == ''
- fail: msg="admin list is empty"
  when: jupyterhub_admins|length == 0

# - name: Create JupyterHub service folder
#   file: path={{ item[0] }} state={{ item[1] }}
#   with_nested:
#     - [ /srv/jupyterhub, /srv/jupyterhub_users ]
#     - [ absent, directory ]

# - name: Copy JupyterHub docker file to server
#   copy: 
#     src={{ item[1] }}/{{ item[0] }}
#     dest={{ item[2] }}/{{ item[0] }}
#   with_nested:
#     - [ Dockerfile, jupyterhub_conf.py ]
#     - [ jupyterhub ]
#     - [ /srv/jupyterhub ]

- name: Copy jupyterhub to host OS
  copy:
    src=jupyterhub
    dest=/srv
    mode='0644'

- name: create the userlist
  template: src=userlist.j2 dest=/srv/jupyterhub_users/userlist
