---
- fail: msg="configproxy_auth_token is not defined"
  when: configproxy_auth_token == ''
- fail: msg="cookie_secret is not defined"
  when: cookie_secret == ''
- fail: msg="admin list is empty"
  when: jupyterhub_admins|length == 0

# - name: clone the dockerfile git repository
#   git: repo=https://github.com/compmodels/jupyterhub.git dest=/srv/jupyterhub

# - name: create the jupyterhub_users directory
#   file: path=/srv/jupyterhub_users state=directory

# - name: create the userlist
#   template: src=userlist.j2 dest=/srv/jupyterhub_users/userlist
