---
# tasks file for docker-jupyterhub

# Check sensitive variable definition.
- include: check_variables.yml

# Place the configuration files inside the folder structure
- include: folder_structure.yml

# Build Docker images
- include: docker_images.yml

# Launch Docker containers
- include: docker_containers.yml
