---
# tasks file for docker-jupyterhub

# Check sensitive variable definition.
- include: check_variables.yml

# Place the configuration files inside the folder structure
# - include: docker_jupyterhub_file_structure.yml

# - fail: msg="jupyterhub_admin_user is not defined"
#   when: jupyterhub_admin_user == ''

# - include: jupyterhub.yml
# - include: stats.yml
# - include: cull.yml

# - name: Copy docker-compose file
#   template: 
#     src=docker-compose.j2
#     dest=/srv/jupyterhub/docker-compose.yml

# - name: stop docker containers
#   command: docker-compose -f /srv/jupyterhub/docker-compose.yml stop

# - name: remove docker containers
#   command: docker-compose --file /srv/jupyterhub/docker-compose.yml rm \
#                           --force --all

# - name: pull docker images
#   command: docker-compose --file /srv/jupyterhub/docker-compose.yml pull

# - name: build docker images
#   command: docker-compose --file /srv/jupyterhub/docker-compose.yml build

# - name: run jupyterhub
#   command: docker-compose up -d jupyterhub
