---
# tasks file for jupyterhub
- fail: msg="jupyterhub_admin_user is not defined"
  when: jupyterhub_admin_user == ''

- include: jupyterhub.yml
- include: stats.yml
- include: cull.yml

- name: Copy docker-compose file
  template: 
    src=docker-compose.j2
    dest=/srv/jupyterhub/docker-compose.yml